language: node_js
node_js:
  - '16'

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - zip -r -q build_artifact.zip .

before_deploy:
  - pip install --user awscli 

deploy:
  provider: script
  script: |
    aws s3 cp build_artifact.zip s3://travisdemobuilds/ # Upload the ZIP file to S3
    # Now deploy the ZIP from S3 to Elastic Beanstalk
    aws elasticbeanstalk create-application-version \
      --application-name travis1 \
      --version-label v1.0 \
      --source-bundle S3Bucket="travisdemobuilds",S3Key="build_artifact.zip"
    aws elasticbeanstalk update-environment \
      --environment-name Travis1-env \
      --version-label v1.0
  skip_cleanup: true
  on:
    branch: main
