language: node_js
node_js:
  - '16'

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - pwd
  - ls -la 
  - ls -al build/
  - zip -r -q build_artifact.zip .
before_deploy:
  - pip install --user awscli # Install AWS CLI using pip
  
deploy:
  provider: script
  script: aws s3 cp --recursive build_artifact.zip s3://travisdemobuilds
  skip_cleanup: true
  on:
    branch: main
