language: node_js
node_js:
  - '16'

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - pwd
  - ls -la 
  - ls -al build/
  - zip -r -q build_artifact.zip .
  - pwd
  - ls -al

before_deploy:
  - pip install --user awscli 
  
deploy:
  provider: script
  script: aws s3 cp /home/travis/build/maheshkaldhone/aws-portfolio/build_artifact.zip s3://travisdemobuilds
  skip_cleanup: true
  on:
    branch: main
