version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing

  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - npm install     

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - echo '#!/bin/bash' > fetch_params.sh
      - echo 'aws ssm get-parameters-by-path --path "/test/" --recursive --with-decryption --output text --query "Parameters[*].{Name:Name,Value:Value}" > tmp_env.txt' >> fetch_params.sh
      - echo 'awk -F"\t" '\''{sub("/test/", "", $1); print $1 "=" $2}'\'' tmp_env.txt > .env' >> fetch_params.sh
      - chmod +x fetch_params.sh
      - ./fetch_params.sh
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`
      - TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
      - VERSION="FE-${TIMESTAMP}"
      - echo "${VERSION}" > .version  

artifacts:
  files:
    - Images/**/*
    - public/**/*
    - scripts/**/*
    - src/**/*
    - appspec.yml
    - package-lock.json
    - package.json
    - .env    
    - .version 
  name: FE-$(date +%Y-%m-%d-%H-%M-%S)  
