name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:  
  Build:
    name: 'Build the code'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

  CodeQuality:
    name: Code quality scan 
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    needs: Build
  
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript'] 
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
        
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  docker_build:
    runs-on: ubuntu-latest
    needs: [Build, CodeQuality ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
              
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
              
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: maheshk31/npm

      - name: Send Push Notification
        uses: techulus/push-github-action@1.0.0
        env:
            API_KEY: ${{ secrets.API_KEY }}
            MESSAGE: "There is a new commit!"


   
